version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  web:
    build:
      context: ./client
    image: 'todo_app_swarm:${APP_VERSION}'
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
      - '${NGINX_HOST_HTTPS_PORT}:443'
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - nest

  nest:
    build:
      context: ./server
    image: 'todo_app_swarm_back:${APP_VERSION}'
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - frontend
      - backend
