version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  web:
    build:
      context: ./VPS_init
      dockerfile: Dockerfile.front
    image: 'todo_app_swarm_web:dev-${APP_VERSION}'
    ports:
      - 4200:4200
    volumes:
      - 'extensions:/root/.vscode-server'
      - 'src:/app'

  nest:
    build:
      context: ./VPS_init
      dockerfile: Dockerfile.back
    image: 'todo_app_swarm_back:dev-${APP_VERSION}'
    volumes:
      - 'extensions_nest:/root/.vscode-server'
      - 'src:/app'
<<<<<<< HEAD
    ports:
      - 3000:3000
=======
>>>>>>> 1ea6ca20c466db8119038d9f26196b532f4c2e88

volumes:
  extensions:
  extensions_nest:
  src:
