version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    build:
      context: ./client
    image:
      'todo_app_swarm:${APP_VERSION}'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    networks:
      - frontend
      - backend
